using System;
using MedMatch.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
namespace MedMatch.Infrastructure.Persistence.Migrations;

[DbContext(typeof(MedMatchDbContext))]
[Migration("202609080001_InitialCreate")]
public partial class InitialCreate : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(name: "clinics", columns: table => new { Id = table.Column<Guid>(nullable: false), Name = table.Column<string>(maxLength: 200, nullable: false), Type = table.Column<string>(nullable: false), Specialty = table.Column<string>(maxLength: 150, nullable: false), TreatmentsOffered = table.Column<string[]>(type: "text[]", nullable: false), Address = table.Column<string>(nullable: true), City = table.Column<string>(maxLength: 120, nullable: false), Country = table.Column<string>(maxLength: 120, nullable: false), Latitude = table.Column<decimal>(nullable: true), Longitude = table.Column<decimal>(nullable: true), ContactInfo = table.Column<string>(nullable: true), IsVerified = table.Column<bool>(nullable: false) }, constraints: table => table.PrimaryKey("PK_clinics", x => x.Id));
        migrationBuilder.CreateTable(name: "messages", columns: table => new { Id = table.Column<Guid>(nullable: false), FromUserId = table.Column<Guid>(nullable: false), ToUserId = table.Column<Guid>(nullable: false), ThreadId = table.Column<Guid>(nullable: false), Content = table.Column<string>(nullable: false), CreatedAt = table.Column<DateTimeOffset>(nullable: false), ConsentSnapshot = table.Column<string>(nullable: false) }, constraints: table => table.PrimaryKey("PK_messages", x => x.Id));
        migrationBuilder.CreateTable(name: "users", columns: table => new { Id = table.Column<Guid>(nullable: false), Email = table.Column<string>(maxLength: 320, nullable: false), PasswordHash = table.Column<string>(nullable: false), Role = table.Column<string>(maxLength: 20, nullable: false), CreatedAt = table.Column<DateTimeOffset>(nullable: false), LastLogin = table.Column<DateTimeOffset>(nullable: true) }, constraints: table => table.PrimaryKey("PK_users", x => x.Id));
        migrationBuilder.CreateTable(name: "doctors", columns: table => new { Id = table.Column<Guid>(nullable: false), ClinicId = table.Column<Guid>(nullable: true), Name = table.Column<string>(maxLength: 200, nullable: false), Specialty = table.Column<string>(maxLength: 150, nullable: false), TreatmentsOffered = table.Column<string[]>(type: "text[]", nullable: false), City = table.Column<string>(nullable: true), Country = table.Column<string>(nullable: true), ContactInfo = table.Column<string>(nullable: true), IsVerified = table.Column<bool>(nullable: false) }, constraints: table => { table.PrimaryKey("PK_doctors", x => x.Id); table.ForeignKey("FK_doctors_clinics_ClinicId", x => x.ClinicId, "clinics", "Id", onDelete: ReferentialAction.SetNull); });
        migrationBuilder.CreateTable(name: "consent_settings", columns: table => new { UserId = table.Column<Guid>(nullable: false), ShowProfilePublicly = table.Column<bool>(nullable: false), ClinicsContactMe = table.Column<bool>(nullable: false), PatientsContactMe = table.Column<bool>(nullable: false), DataForSearch = table.Column<bool>(nullable: false), Version = table.Column<int>(nullable: false), UpdatedAt = table.Column<DateTimeOffset>(nullable: false), Ip = table.Column<string>(maxLength: 64, nullable: true), UserAgent = table.Column<string>(maxLength: 512, nullable: true) }, constraints: table => { table.PrimaryKey("PK_consent_settings", x => x.UserId); table.ForeignKey("FK_consent_settings_users_UserId", x => x.UserId, "users", "Id", onDelete: ReferentialAction.Cascade); });
        migrationBuilder.CreateTable(name: "patient_profiles", columns: table => new { UserId = table.Column<Guid>(nullable: false), DisplayMode = table.Column<string>(maxLength: 20, nullable: false), Pseudonym = table.Column<string>(nullable: true), RealName = table.Column<string>(nullable: true), City = table.Column<string>(nullable: true), Country = table.Column<string>(nullable: true), Diagnoses = table.Column<string[]>(type: "text[]", nullable: false), Interventions = table.Column<string[]>(type: "text[]", nullable: false), Symptoms = table.Column<string[]>(type: "text[]", nullable: false), AgeRange = table.Column<string>(nullable: true), Bio = table.Column<string>(nullable: true), Languages = table.Column<string[]>(type: "text[]", nullable: false) }, constraints: table => { table.PrimaryKey("PK_patient_profiles", x => x.UserId); table.ForeignKey("FK_patient_profiles_users_UserId", x => x.UserId, "users", "Id", onDelete: ReferentialAction.Cascade); });
        migrationBuilder.CreateTable(name: "refresh_tokens", columns: table => new { Id = table.Column<Guid>(nullable: false), UserId = table.Column<Guid>(nullable: false), TokenHash = table.Column<string>(maxLength: 128, nullable: false), ExpiresAt = table.Column<DateTimeOffset>(nullable: false), RevokedAt = table.Column<DateTimeOffset>(nullable: true) }, constraints: table => { table.PrimaryKey("PK_refresh_tokens", x => x.Id); table.ForeignKey("FK_refresh_tokens_users_UserId", x => x.UserId, "users", "Id", onDelete: ReferentialAction.Cascade); });
        migrationBuilder.CreateTable(name: "reviews", columns: table => new { Id = table.Column<Guid>(nullable: false), AuthorUserId = table.Column<Guid>(nullable: false), ClinicId = table.Column<Guid>(nullable: true), DoctorId = table.Column<Guid>(nullable: true), Rating = table.Column<int>(nullable: false), Title = table.Column<string>(maxLength: 200, nullable: false), Body = table.Column<string>(nullable: false), Tags = table.Column<string[]>(type: "text[]", nullable: false), IsAnonymous = table.Column<bool>(nullable: false), AllowContactByPatients = table.Column<bool>(nullable: false), AllowContactByClinics = table.Column<bool>(nullable: false), CreatedAt = table.Column<DateTimeOffset>(nullable: false), UpdatedAt = table.Column<DateTimeOffset>(nullable: false) }, constraints: table => { table.PrimaryKey("PK_reviews", x => x.Id); table.CheckConstraint("CK_reviews_rating", "\"Rating\" BETWEEN 1 AND 5"); table.ForeignKey("FK_reviews_users_AuthorUserId", x => x.AuthorUserId, "users", "Id", onDelete: ReferentialAction.Cascade); table.ForeignKey("FK_reviews_clinics_ClinicId", x => x.ClinicId, "clinics", "Id", onDelete: ReferentialAction.SetNull); table.ForeignKey("FK_reviews_doctors_DoctorId", x => x.DoctorId, "doctors", "Id", onDelete: ReferentialAction.SetNull); });
        migrationBuilder.CreateIndex("IX_consent_settings_UserId", "consent_settings", "UserId"); migrationBuilder.CreateIndex("IX_doctors_ClinicId", "doctors", "ClinicId"); migrationBuilder.CreateIndex("IX_messages_ThreadId_CreatedAt", "messages", new[] { "ThreadId", "CreatedAt" }); migrationBuilder.CreateIndex("IX_refresh_tokens_TokenHash", "refresh_tokens", "TokenHash", unique: true); migrationBuilder.CreateIndex("IX_refresh_tokens_UserId", "refresh_tokens", "UserId"); migrationBuilder.CreateIndex("IX_reviews_AuthorUserId", "reviews", "AuthorUserId"); migrationBuilder.CreateIndex("IX_reviews_ClinicId", "reviews", "ClinicId"); migrationBuilder.CreateIndex("IX_reviews_DoctorId", "reviews", "DoctorId"); migrationBuilder.CreateIndex("IX_users_Email", "users", "Email", unique: true);
    }
    protected override void Down(MigrationBuilder migrationBuilder) { migrationBuilder.DropTable("consent_settings"); migrationBuilder.DropTable("messages"); migrationBuilder.DropTable("patient_profiles"); migrationBuilder.DropTable("refresh_tokens"); migrationBuilder.DropTable("reviews"); migrationBuilder.DropTable("doctors"); migrationBuilder.DropTable("users"); migrationBuilder.DropTable("clinics"); }
}
